import type { Metadata, Viewport } from "next";

import "./globals.css";
import StoreProvider from "@/store/store-provider";

export const metadata: Metadata = {
  title: "Guess Salt Score",
  description: "Generated by blue holding company"
};

export const viewport: Viewport = {
  viewportFit: 'cover'
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <StoreProvider>
      <html lang="en" className="h-full">
        <body className="h-full">{children}</body>
      </html>
    </StoreProvider>
  );
}