import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Guess Salt Score",
  description: "Generated by blue holding company",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full">{children}</body>
    </html>
  );
}